// Generated by ToffeeScript 1.4.0
(function() {
  var curl, p,
    _this = this;

  curl = require('../index');

  p = console.info;

  curl(process.argv[2], {
    VERBOSE: 1,
    DEBUG: 1
  }, function(_$$_err, _$$_res) {
    var err, res;
    err = _$$_err;
    res = _$$_res;
    if (err) {
      return p(err);
    } else {
      return p(res);
    }
  });

}).call(this);
