// Generated by ToffeeScript 1.6.2
(function() {
  var curl, err, p, res,
    _this = this;

  curl = require('../index');

  p = console.info;

  curl(process.argv[2], {
    VERBOSE: 1,
    DEBUG: 1
  }, function() {
    err = arguments[0], res = arguments[1];
    if (err) {
      return p(err);
    } else {
      return p(res);
    }
  });

}).call(this);
