// Generated by ToffeeScript 1.2.0-0
(function() {
  var assert, curl, i, j, next, once, _i;

  curl = require('../index');

  assert = require('assert');

  j = 0;

  (next = function() {
    console.info("curl instances: ", curl.get_count());
    return setTimeout(next, 1000);
  })();

  for (i = _i = 1; _i <= 100; i = ++_i) {
    (once = function() {
      var _this = this;
      return curl('localhost/test.html', function(_$$_err, _$$_res) {
        var err, res;
        err = _$$_err;
        res = _$$_res;
        assert.equal(res.body.length, 1468);
        if (++j % 100 === 0) console.info(j);
        if (j < 20000) return once();
      });
    })();
  }

}).call(this);
