// Generated by ToffeeScript 1.6.2-5
(function() {
  var cookieFile, curl, err, fs, options, p, stream, util,
    _this = this;

  curl = require('../index');

  fs = require('fs');

  util = require('util');

  p = console.info;

  cookieFile = 'node-curl-cookie.txt';

  options = {
    VERBOSE: 1,
    COOKIEFILE: cookieFile,
    COOKIEJAR: cookieFile,
    ACCEPT_ENCODING: 'gzip',
    RAW: 1
  };

  curl.debug = 1;

  curl.setDefaultOptions(options);

  curl('www.google.com', function() {
    err = arguments[0];
    p("\x1b[33m" + util.inspect(curl.info('COOKIELIST')) + "\x1b[0m");
    curl.reset();
    curl('www.yahoo.com', function() {
      err = arguments[0];
      p("\x1b[33m" + util.inspect(curl.info('COOKIELIST')) + "\x1b[0m");
      p("body length " + curl.body.length);
      p("\x1b[33mText in " + cookieFile + "\x1b[0m");
      p("----");
      stream = fs.createReadStream(cookieFile);
      stream.pipe(process.stdout);
      return stream.on('end', function() {
        var _this = this;
        p("----");
        curl.close();
        p("deleting " + cookieFile);
        fs.unlink(cookieFile, function() {
          return p("done.");
        });
      });
    });
  });

}).call(this);
