#!/bin/sh

root=`dirname $0`

if [ "$NODE_CURL_H" != "" ] ; then
  if [ ! -f "$NODE_CURL_H" ] ; then
    echo "cannot find curl's header file $NODE_CURL_H ."
    exit 1
  fi
  curl_header=$NODE_CURL_H
elif [ -f "/usr/local/include/curl/curl.h" ] ; then
  curl_header="/usr/local/include/curl/curl.h"
elif [ -f "/usr/include/curl/curl.h" ] ; then
  curl_header="/usr/include/curl/curl.h"
fi

echo "extract constants from $curl_header"

generate() {
  name=$1
  pattern=$2
  prefix=$3
  echo "generate $root/$name.h"
  (
    echo "// generated by $0 at $(date)"
    echo "CurlOption $name[] = {"
    cat "$curl_header"|perl -ne "/$pattern/i && print \"\t{\\\"\$1\\\", CURL${prefix}_\$1},\n\""
    echo '};'
  ) > $root/$name.h
}
generate integer_options 'CINIT\((\w+).*LONG' OPT
generate string_options  'CINIT\((\w+).*OBJECT' OPT

generate integer_infos 'CURLINFO_(\w+).*LONG' INFO
generate string_infos 'CURLINFO_(\w+).*STRING' INFO
generate double_infos 'CURLINFO_(\w+).*DOUBLE' INFO
