name: Release new version of node-libcurl

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version to release'
        required: true

env:
  # Release Tag to build and publish
  TAG: ${{ github.event.inputs.version }}

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@266845213695c3047d210b2e8fbc42ecdaf45802 # master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'insomnia-infra' }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci --ignore-scripts

      - name: Create new package version
        run: npm version "${{ env.TAG }}"

      - name: DEBUG see tags
        run: |
          git tag --list
          git remote -v

      - name: Merge version commit into develop
        run: |
          git push origin v${{ env.TAG }}
          git push origin develop

      - name: Create Tag and Release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1
        id: core_tag_and_release
        with:
          tag: v${{ env.TAG }}
          name: "nodelibcurl v${{ env.TAG }} 📦"
          generateReleaseNotes: true
          prerelease: false
          draft: false
