name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-18.04
    permissions: 
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        node:
          - 12
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: yarn install --ignore-scripts
      - name: Build
        run: yarn build:dist
      - name: Publish Package
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
